import '../globals.css'

export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        <h1>Sistema Geral</h1>
        {children}
        </body>
    </html>
  )
}
